version: '3.8'
services:
  postgres_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: open_banking_core
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis_db:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: celery -A src.worker.celery_app worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://redis_db:6379/0
      - DATABASE_URL=postgresql://admin:rootpassword@postgres_db:5432/open_banking_core
    depends_on:
      - redis_db
      - postgres_db

volumes:
  pgdata:
